#!/bin/sh

set -e

CFLAGS="-Werror -DPROJ_RENAME_SYMBOLS" CXXFLAGS="-Werror -DPROJ_RENAME_SYMBOLS" LDFLAGS='-lstdc++' cmake .. -DUSE_CCACHE=ON -DPROJ_ROOT=/usr/local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DGDAL_USE_GEOTIFF_INTERNAL:BOOL=ON -DGDAL_USE_TIFF_INTERNAL:BOOL=ON

make -j3
